---
# tasks file for kubernetes_cluster

 - include_vars:
         file: vars/aws_key.yml
         name: aws

 - name: "Create a Custom Key_Pair for EC2"
   ec2_key:
           aws_access_key: "{{ aws.access_key }}"
           aws_secret_key: "{{ aws.secret_key }}"
           key_material: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
           state: present
           name: "key-1"


 - name: "Provisioning 1 Instance for Master Node"
   ec2_instance:
           aws_access_key: "{{ aws.access_key }}"
           aws_secret_key: "{{ aws.secret_key }}"
           region: ap-south-1
           image_id: ami-08f63db601b82ff5f
           instance_type: t2.micro
           state: present
           name: "Kube-Master"
           key_name: "key-1"
   register: x1

 - name: "Provisioning 1st Instance for Worker Node"
   ec2_instance:
           aws_access_key: "{{ aws.access_key }}"
           aws_secret_key: "{{ aws.secret_key }}"
           region: ap-south-1
           image_id: ami-08f63db601b82ff5f
           instance_type: t2.micro
           state: present
           name: "Kube-Worker-1"
           key_name: "key-1"
   register: x2

 - name: "Provisioning 2nd other Instance for Worker Node"
   ec2_instance:
           aws_access_key: "{{ aws.access_key }}"
           aws_secret_key: "{{ aws.secret_key }}"
           region: ap-south-1
           image_id: ami-08f63db601b82ff5f
           instance_type: t2.micro
           state: present
           name: "Kube-Worker-2"
           key_name: "key-1"
   register: x3

 - name: "Add all those Instance's IP Address in Inventory"
   blockinfile:
           path: "/root/inven_ansible"
           block: |
                   [Kube_Master_node]
                   {{ x1.instances[0].network_interfaces[0].association['public_ip'] }} ansible_user=ec2-user ansible_ssh_private_key_file=/root/.ssh/id_rsa.pub ansible_connection=ssh
                   [Kube_Worker_node]
                   {{ x2.instances[0].network_interfaces[0].association['public_ip'] }} ansible_user=ec2-user ansible_ssh_private_key_file=/root/.ssh/id_rsa.pub ansible_connection=ssh
                   {{ x3.instances[0].network_interfaces[0].association['public_ip'] }} ansible_user=ec2-user ansible_ssh_private_key_file=/root/.ssh/id_rsa.pub ansible_connection=ssh


 - meta: refresh_inventory


